stages:
  - scrape

run_scraper:
  image: mcr.microsoft.com/playwright/python:v1.40.0-jammy
  stage: scrape
  script:
    - pip install "playwright==1.40.0"
    - python scraper.py
  artifacts:
    expire_in: 1 days
    paths:
      - horarios_micros.json
      - paso_1_inicio.png
      - paso_2_panel.png
      - paso_3_final.png